--- 
- hosts: all 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present 

  - name: copy static file into node side 
    copy:
      src: mystaticfile
      dest: /home/ubuntu/mystaticfile
  - name: download file and force basic auth
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes
   