--- 
- hosts: all
  become: yes

  tasks:
  - name: Install the package "git"
    apt:
     name: git
     state: present

  - name: Install the package wget
    apt:
     name: wget
     state: absent