--- 
- hosts: mywebserver
  become: yes

  tasks:
  - name: Install the package "apache2"
    apt:
     name: "{{mywebpackonubantu}}"
     state: present
    when: ansible_os_family =="Debian" 

  - name: Start service apache2, on node server
    service:
      name: "{{mywebpackonubantu}}"
      state: started  
    when: ansible_os_family =="Debian" 

  - name: Install the package "java"
    apt:
     name: "{{myjavapackonubantu}}"
     state: present
    when: ansible_os_family =="Debian" 
  